version: '3.7'

services:
  testdb:
    image: postgres:14-alpine
    container_name: testdb
    hostname: testdb
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tester
    restart: always
    volumes:
      - test-database-data:/var/lib/postgresql/data

  test-web:
    container_name: test-web
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: on-failure
    depends_on:
      - testdb
    env_file:
      - .env.test
    ports:
      - '3000:3000'
    command: sh -c "./wait-for-it.sh testdb:5432 -- yarn prisma migrate deploy && yarn prisma generate && yarn dev"
    volumes:
      - ./src:/app/src

volumes:
  test-database-data:
