version: '3.7'

services:
  database:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-project}
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
