# prisma still not support  https://github.com/prisma/prisma/issues/8478
FROM node:16.14-buster-slim

RUN apt-get update && \
    apt-get install openssl -y && \
    apt-get clean

WORKDIR /app

COPY wait-for-it.sh ./wait-for-it.sh

RUN chmod +x ./wait-for-it.sh

COPY .env.test ./.env

COPY package.json ./

COPY yarn.lock ./

RUN yarn

COPY . .

EXPOSE 3000
